Learn_Django/urls.py
"""Configura las URLs para ambas vistas (API y con templates)."""

from django.urls import path

app_name = "books"

urlpatterns = [

]

books/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("books/urls"), namespace='books'),
]

practice2/urls.py
from django.urls import path, include
from rest_framework import routers

from practice2 import views

router = routers.DefaultRouter()
router.register(r'tarea', views.TareaViewSet)
router.register(r'tarea2', views.TareaViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('', views.lista_tareas, name='lista_tareas'),
    path('lista', views.ListaTarea.as_view(), name='lista_tareas2'),
    path('delete/<int:tarea_id>', views.borrar_tareas, name='delete'),
    path('api/lista_tareas/', views.TareaViewSet.as_view({'get': 'list'}), name='lista_tareas_api_view'),
    path('api/lista_tareas/<int:pk>', views.TareaViewSet.as_view({'get': 'retrieve'}), name='tareas_api_view'),
    path('new', views.create_task_form, name='create_task'),
    path('new2', views.CreateTask.as_view(), name='new_create_task'),
]

app_name = "practice2"

Practices/models.py
from django.db import models
#models.py
# Modelo:
# Crea un modelo llamado Producto con campos como nombre, precio y cantidad en stock.
# QuerySet:
# Implementa un QuerySet que filtre los productos con un precio mayor a $50.


class Product(models.Model):
    name = models.CharField(max_length=40)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock_quantity = models.PositiveIntegerField()

books/models.py
from django.db import models

""" Libro: Atributos: Título, Autor, ISBN, Descripción, Disponibilidad (booleano). 
Métodos: prestar(), devolver().

Usuario: Atributos: Nombre, Apellido, Email. 
Relación con Libro: Muchos a muchos 
(un usuario puede tener varios libros prestados, y un libro puede estar prestado a varios usuarios). """


class Book(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    author = models.CharField(max_length=100, blank=True, null=True)
    isbn = models.CharField(max_length=17, blank=False, null=False)
    description = models.CharField(max_length=400, blank=True, null=True)
    availability = models.BooleanField(default=True)


class User(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    surname = models.CharField(max_length=50, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    book = models.ManyToManyField(Book, on_delete=models.CASCADE, )

practice2/models.py
from django.db import models

# Modelo: Crea un modelo ea un modelo llamado Tarea con los siguientes campos:
# titulo (CharField)
# descripcion (TextField)
# fecha_creacion (DateField)
# completada (BooleanField)


class Tarea(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=300)
    fecha_creacion = models.DateField(auto_now=True)
    completada = models.BooleanField(default=False)

    class Meta:
        ordering = ('fecha_creacion', )

practice2/forms/create_task_form.py
from django import forms

from practice2.models import Tarea


class TareaForm(forms.ModelForm):
    class Meta:
        model = Tarea
        fields = ['titulo', 'descripcion']

Practices/views.py
from Practices.models import Product
from django.shortcuts import render
# views.py

# la realidad es que el metodo no devuelve una lista sino una respuesta donde apunto a una vista html
# a la cual le pasas la lista


def up_to_50_euros(request):

    # traer de la bbdd todos los productor que cumplan esta condicion mayor igual...
    # "crear la lista para mandar" - no hace falta ya que la respuesta de queryset ya te lo trae en forma de lista

    listo_of_products_up_to_50 = Product.objects.filter(price__gte=50)

    return render(request, 'template.html', {'listo_of_products_up_to_50': listo_of_products_up_to_50})

books/views.py
from django.shortcuts import render

""" Página principal: Lista de todos los libros disponibles con enlaces a detalles. 
Página de detalles del libro: Información detallada del libro. Botones para prestar o devolver el libro 
(si está disponible o prestado). Página de búsqueda: Formulario de búsqueda por título o autor. 
Resultados de búsqueda con enlaces a detalles."""

practice2/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView
from rest_framework import viewsets

from .forms.create_task_form import TareaForm
from .models import Tarea
from .serializes import MinTareaSerializer



# Crea una vista basada en clase llamada ListaTareasAPIView que liste todas las tareas.
# (Utiliza el serializador TareaSerializer y el modelo Tarea).
# Crea una vista llamada lista_tareas que renderice un template lista_tareas.html.
# (Esta vista debe mostrar todas las tareas.)

# para uso de front externos


class TareaViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Tarea.objects.all()
    serializer_class = MinTareaSerializer


class ListaTarea(TemplateView):
    template_name = 'lista_tareas.html'

    def get_context_data(self, **kwargs):
        list_all_task = Tarea.objects.all().distinct()
        return {'list_all_task': list_all_task}


# uso con las pantillas de django
def lista_tareas(request):
    # list_all_task = Tarea.objects.all().order_by('-fecha_creacion')
    list_all_task = Tarea.objects.all().distinct()

    return render(request, 'lista_tareas.html', {'list_all_task': list_all_task})


def borrar_tareas(request, tarea_id=None):
    tareas_a_borrar = Tarea.objects.filter(id=tarea_id)
    tareas_a_borrar.delete()
    return redirect(reverse("practice2:lista_tareas"))


def create_task_form(request: HttpRequest) -> HttpResponse:

    form = TareaForm(instance=Tarea.objects.get(), data=request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()

            new_titulo = form.cleaned_data['titulo']
            new_desciption = form.cleaned_data['descripcion']

            new_task = Tarea.objects.create(titulo=new_titulo, descripcion=new_desciption)
            a = Tarea.objects.all()
            for i in a.values('titulo'):
                print(i.titulo)

        else:
            form = TareaForm()

    return render(request, 'create.html', {'form': form})


class CreateTask(TemplateView):
    template_name = 'create.html'

    def get_context_data(self, **kwargs):
        form = TareaForm(self.request.POST)
        return {'form': form}

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        form = context["form"]
        if form.is_valid():
            new_titulo = form.cleaned_data['titulo']
            new_desciption = form.cleaned_data['descripcion']

            new_task = Tarea(titulo=new_titulo, descripcion=new_desciption)
            new_task.save()
        return render(request, self.template_name, context)

practice2/templates/create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Crear Tareas</title>
</head>
<body>

<form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Crear Tarea</button>
</form>

</body>
</html>

practice2/templates/lista_tareas.html
<!--path('lista_tareas/', lista_tareas, name='lista_tareas'),-->
<!-- titulo descripcion fecha_creacion completada -->

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>lLista de Tareas</title>
</head>
<body>
<h2> TASK LIST </h2>
<br>
<div>
    {% if list_all_task %}
        <table>
            <thead>
            <tr>
                <th>Título</th>
                <th>Descripción</th>
                <th>Fecha de Creación</th>
                <th>Completada</th>
                <th>Borrar</th>
            </tr>
            </thead>
            <tbody>
            {% for tarea in list_all_task %}
                <tr>
                    <td>{{ tarea.titulo }}</td>
                    <td>{{ tarea.descripcion }}</td>
                    <td>{{ tarea.fecha_creacion }}</td>
                    <td>{{ tarea.completada }}</td>
                    <td> <a href="{% url "practice2:delete" tarea_id=tarea.id %}">Borrar</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert">
            <h5>No hay tareas disponibles.</h5>
        </div>
    {% endif %}

</div>



</body>
</html>